name: CollabHub CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint-backend:
    name: Backend Build & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: ./backend/package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Prisma Generate
      run: npx prisma generate
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build

  build-and-lint-frontend:
    name: Frontend Build & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
